### ISSUE TITLE
Add support for a `match` pipe

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr-core#1]
Follow up to [this conversation](https://github.com/loreanvictor/tmplr/issues/3#issuecomment-1475146011), it would be useful to add a `match()` pipe that would return the input string if it matches the reference and an empty string if not. It will be useful in constructs such as this:

```yaml
if:
  eval: '{{ var | matches: value }}'
steps:
  # do stuff ...
```

<br>

Note that this is kind of a work-around for advanced conditional expressions (`if x == y`). In case that type of expression is ever implemented, it is possible that this feature should be deprecated to keep API surface minimal.
