### ISSUE TITLE
`if` should be an expression

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr-core#5]
There is no utility to conditionally evaluate an expression. A pragmatic example would be calculating a URL for the project when `git.remote_provider` contextual value exists. If `if` command acted like an expression instead of a command, then it would satisfy this requirement as well:

```yaml
prompt: What is the project URL?
default:
  if: git.remote_provider
  eval: 'https://{{ git.remote_provider }}/{{ git.remote_owner }}/{{ git.remote_name }}'
```
